# Generated by Django 6.0.1 on 2026-02-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='elevator_coeff',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='heating_coeff',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
