# Generated by Django 6.0.1 on 2026-02-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_apartment_elevator_coeff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('elevator', 'Elevator'), ('electricity', 'Electricity'), ('water', 'Water'), ('heating', 'Heating'), ('repairs', 'Repairs'), ('gardening', 'Gardening'), ('other', 'Other')], max_length=20),
        ),
    ]
