# Generated by Django 6.0.1 on 2026-02-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('elevator', 'Elevator'), ('electricity', 'Electricity'), ('water', 'Water'), ('heating', 'Heating'), ('repairs', 'Repairs'), ('gardening', 'Gardening'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
